language: java
jdk:
  - oraclejdk8
services:
  - mongodb
before_install:
  - curl https://www.jpm4j.org/install/script | sh
  - jpm install com.codacy:codacy-coverage-reporter:assembly
before_script:
  - mongo pollistics --eval 'db.polls.insert({"name":"Amerikaanse verkiezingen","options":{"trump":206,"clinton":2}})'
  - mongo pollistics --eval 'db.polls.insert({"name":"Favoriet kleur","options":{"root":1,"blauw":80}})'
after_success:
  - codacy-coverage-reporter -l Java -r coverage.xml
