language: java
jdk:
  - oraclejdk8
services:
  - mongodb
before_install:
  - mkdir installers && curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar > installers/jpm4j.jar
  - java -jar installers/jpm4j.jar -u init && rm -r installers && export PATH=$PATH:$HOME/jpm/bin
  - jpm install com.codacy:codacy-coverage-reporter:assembly
before_script:
  - mongo pollistics --eval 'db.polls.insert({"title":"Amerikaanse verkiezingen","options":{"trump":206,"clinton":2}})'
  - mongo pollistics --eval 'db.polls.insert({"title":"Favoriet kleur","options":{"root":1,"blauw":80}})'
  - mongo pollistics --eval 'db.users.insert({"name":"some-user","password":"$2a$10$rAzmBTawjivQDfTDzZFaQOoGwFhnA4mt7VuWpkWhdLKQFlY/0m3bm"})'
after_success:
  - codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
